[package]
name = "ironstore-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ironstore-cli"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
clap = "4.5.1"
