[package]
name = "ironstore-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ironstore-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
clap = "4.5.1"
log = "0.4"
simplelog = "0.12.2"
